NovskyProject/NovskyProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("visuals.urls")),
    path("admin/", admin.site.urls),
]

NovskyProject/visuals/urls.py
from django.urls import path, include, re_path
from . import views
from rest_framework import routers


# for rest api
router = routers.DefaultRouter()
router.register(r"visuals", views.VisualViewSet)

app_name = "visuals"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("api/", include(router.urls), name="api"),
    path("markdownx/", include("markdownx.urls")),
]

NovskyProject/visuals/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
import json
import logging

logger = logging.getLogger(__name__)
logger.setLevel(logging.WARNING)


class VizType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class VizResource(models.Model):
    """resources use to cite and give credit"""

    name = models.CharField(max_length=100)
    url = models.URLField(max_length=400)
    description = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Visual(models.Model):
    name = models.CharField(max_length=100)
    viz_type = models.ForeignKey(
        VizType, related_name="type", on_delete=models.CASCADE, null=True, blank=True
    )
    body = models.TextField(help_text="should be javascript or html")
    summary = MarkdownxField(blank=True)
    viz_description = models.CharField(
        max_length=400,
        null=True,
        blank=True,
        help_text="help explain the viz iteself, ie x axis represents ...",
    )
    pub_date = models.DateTimeField("date published")
    tags = models.ManyToManyField(Tag, related_name="tag")
    viz_resources = models.ForeignKey(
        VizResource,
        related_name="resource",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    @property
    def formatted_markdown(self):
        return markdownify(self.summary)

    def __str__(self):
        return self.name

    @property
    def viz_json(self) -> str:
        return json.loads(self.body)

    @property
    def background_color(self):
        try:
            if self.viz_type.name.upper() == "ALTAIR":
                return self.viz_json.get("config").get("background")
            if self.viz_type.name.upper() == "PLOTLY":
                return (
                    self.viz_json.get("data")[2].get("cells").get("fill").get("color")
                )
        except Exception as e:
            default_color = "grey"
            logger.warning(
                f"{self.viz_type} viz background defaulting to {default_color} - Warning Message: {e}"
            )
            return default_color

    @property
    def font_color(self):
        try:
            if self.viz_type.name.upper() == "ALTAIR":
                return self.viz_json.get("config").get("title").get("color")
            if self.viz_type.name.upper() == "PLOTLY":
                return (
                    self.viz_json.get("data")[0].get("cells").get("font").get("color")
                )
        except Exception as e:
            default_color = "white"
            logger.warning(
                f"{self.viz_type} viz font color defaulting to {default_color} - Warning Message: {e}"
            )
            return default_color

NovskyProject/visuals/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Tag, Visual
from .serializers import VisualSerializer
from rest_framework import viewsets


class IndexView(generic.ListView):
    template_name = "visuals/index.html"
    context_object_name = "latest_visual_list"
    paginate_by = 10

    def get_queryset(self):
        """Return the last five published questions."""
        return Visual.objects.order_by("-pub_date")


class DetailView(generic.DetailView):
    model = Visual
    context_object_name = "visual"
    template_name = "visuals/detail.html"


class VisualViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """

    queryset = Visual.objects.all()
    serializer_class = VisualSerializer
    # permission_classes = [permissions.IsAuthenticated]

NovskyProject/visuals/templates/visuals/base.html
{% load static %}
<head>
		{% if DJANGO_SETTINGS.ENV != 'PROD' %}
				<title> {{ DJANGO_SETTINGS.ENV }} - NovskyTech - {{ visual.name }}</title>
		{% else %}
				<title>NovskyTech - {{ visual.name }}</title>
		{% endif %}
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<link rel="shortcut icon" type="image/png" href="{% static 'favicon.jpeg' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		{% block script %} 
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
				<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
		{% endblock script %} 
</head>
{% block content %}{% endblock content %}
<footer style="padding:10px; font-style:italic;"> {{ DJANGO_SETTINGS.version }} </footer>

NovskyProject/visuals/templates/visuals/detail.html
{% extends "visuals/base.html" %}
{% load static %}
{% block script %}
		{% if visual.viz_type.name == 'Altair' %}
				<script src="https://cdn.jsdelivr.net/npm/vega@5.22.1"></script>
				<script src="https://cdn.jsdelivr.net/npm/vega-lite@5.5.0"></script>
				<script src="https://cdn.jsdelivr.net/npm/vega-embed@6.21.0"></script>
		{% elif visual.viz_type.name == 'Plotly' %}
				<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
		{% else %}

		{% endif %}
{% endblock script %}
{% block content %}
		<body style="background:{{visual.background_color}};">
				{% if visual.viz_type.name == 'Altair' %}
						<div class="altair_container" style="display:flex; justify-content:center; align-items:center; height:95%; flex-flow: column;">
								<div id="vis_altair"></div>
								<script type="text/javascript">
										var yourVlSpec = JSON.parse("{{visual.body|escapejs}}");
										vegaEmbed('#vis_altair', yourVlSpec);
								</script>
								{% if visual.summary %}
										<div id="summary" style="background: white; border-color:{{ visual.font_color }};"> 
												{{ visual.formatted_markdown|safe }}
										</div>
								{% endif %}
						</div>
				{% elif visual.viz_type.name == 'Plotly' %}
						<div class="plotly_container">
								{{visual.body|safe}}
								{% if visual.summary %}
										<div id="summary" style="background: white; border-color:{{ visual.font_color }};"> 
												{{ visual.formatted_markdown|safe }}
										</div>
								{% endif %}
						</div>
				{% elif visual.viz_type.name == 'HTML' %}
						{{visual.body | safe}}
				{% else %}
						<h1> ERROR DO NOT RECOGNIZE {{ visual.viz_type.name }}</h1>
				{% endif %}
		{% if visual.viz_description %}
				<div style="color:grey; padding:5px; font-size:25px;"> 
						<i> Chart Description: {{ visual.viz_description }} </i>
				</div>
		{% endif %}
		{% if visual.viz_resources %}
				<div style="color:grey; padding:5px; font-size:25px;"> 
						<i> Chart Source: <a href="{{ visual.viz_resources.url }}">{{ visual.viz_resources.name}} </a> </i>
				</div>
		{% endif %}
		{% comment %}{{ visual.js_post_load|safe }}{% endcomment %}
		</body>
{% endblock content %}

NovskyProject/visuals/templates/visuals/index.html
{% extends "visuals/base.html" %}
{% block content %}
<div style="padding:10px;">
		{% if DJANGO_SETTINGS.ENV != 'PROD' %}
				<div style="background: #FAF884">
						<h1> Visuals - {{ DJANGO_SETTINGS.ENV }} </h1>
						<hr>
						<p> {{ DJANGO_SETTINGS }} </p>
				</div>
		{% else %}
				<h1> Visuals </h1>
		{% endif %}
		<hr>
		<div style="padding:25px; padding-top:0px;">
		{% if latest_visual_list %}
			{% for visual in latest_visual_list %}
			<h3>
				<a href="{% url 'visuals:detail' visual.id %}" style="text-decoration: solid; color:black;">{{ visual.name }}</a>
			</h3>
			<p>
			Tags:
				{% for tag in visual.tags.all %}
						<span class="badge">{{ tag }}</span>
				{% endfor %}
			</p>
			{% endfor %}
		  <nav aria-label="Page navigation conatiner"></nav>
				  <ul class="pagination justify-content-center">
					{% if page_obj.has_previous %}
					<li><a href="?page={{ page_obj.previous_page_number }}" class="page-link" style="color:black;">&laquo; PREV </a></li>
					{% endif %}
					{% if page_obj.has_next %}
					<li><a href="?page={{ page_obj.next_page_number }}" class="page-link" style="color:black;"> NEXT &raquo;</a></li>
					{% endif %}
				  </ul>
		  </nav>
		{% else %}
			<p>No visual are available.</p>
		{% endif %}
		</div>
</div>
{% endblock content %}